import { cpSync, mkdirSync, readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
const root = new URL('../', import.meta.url);
const { version } = JSON.parse(readFileSync(new URL('package.json', root), 'utf8'));
const staging = mkdtempSync(join(tmpdir(), 'shelf-release-'));
const directory = join(staging, `shelf-${version}`);
mkdirSync(directory);
cpSync(new URL('dist/', root), join(directory, 'dist'), { recursive: true });
for (const file of ['package.json', 'LICENSE', 'README.md']) cpSync(new URL(file, root), join(directory, file));
mkdirSync(new URL('release/', root), { recursive: true });
const archive = resolve(`release/shelf-${version}.tar.gz`);
execFileSync('tar', ['-czf', archive, '-C', staging, `shelf-${version}`]);
const digest = createHash('sha256').update(readFileSync(archive)).digest('hex');
writeFileSync(`${archive}.sha256`, `${digest}  shelf-${version}.tar.gz\n`);
console.log(`${archive}\n${digest}`);
